version: '3'

services:
  db:
    image: mysql:8.0
    container_name: mindbut-database
    restart: always
    ports:
      - "8101:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    platform: linux/arm64
